spring.application.name=TDSOA

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/serverdb
spring.datasource.username=oumar
spring.datasource.password=sall0055
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration du serveur
server.port=8080

# Configuration Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
