spring.application.name=TDSOA

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tdsoa_db
spring.datasource.username=oumar
spring.datasource.password=sall12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration du serveur
server.port=8080

# Configuration Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html


# Enable debug logging for web and errors
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.com.td1Rest=DEBUG  

# Pretty-print JSON in logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Show full stack traces
logging.level.root=INFO
